version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - frontend
    environment:
      - API_KEY=PUT_YOUR_API_KEY_HERE
      - WHITELIST_URLS=http://localhost:3000
      - SERVER_PORT=4000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_BASE_URL: http://localhost:4000/api
    ports:
      - 3000:80